# Nombre de tu proyecto
spring.application.name=sistema

# CONFIGURACION DE BASE DE DATOS (Hibrida)
# Localmente usara 'sistema' / En Railway usara la variable de entorno
spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/sistema}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:Joaners1703}

# Driver y Dialecto
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# CONFIGURACION JPA / HIBERNATE
# 'update' crea las tablas automaticamente si no existen
spring.jpa.hibernate.ddl-auto=update
# Muestra las consultas SQL en la consola para que veas que esta pasando
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PUERTO DEL SERVIDOR
# Localmente usa el 8080 / Railway asignara uno automaticamente
server.port=${PORT:8080}
