spring.application.name=sistema

# Si MYSQL_URL no existe, usa el localhost por defecto
spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/nombre_de_tu_db_local}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:tu_password_local}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Lo mismo para el puerto: usa el de Railway o el 8080 local
server.port=${PORT:8080}